export const FETCH_RECIPES_BY_NAME_INITIALIZE = "FETCH_RECIPES_BY_NAME_INITIALIZE";
export const FETCH_RECIPES_BY_NAME_SUCCESS = "FETCH_RECIPES_BY_NAME_SUCCESS";
export const FETCH_RECIPES_BY_NAME_FAIL = "FETCH_RECIPES_BY_NAME_FAIL"